module CAQ {

    typedef sequence<NoxReading> Log_of_alarm_readings;
    typedef sequence<NoxReading> Set_of_readings;

    struct NoxReading {
            long long time;
            long long date;
            string station_name;
            long reading_value;
        };

    interface MonitoringStation {
         readonly attribute string station_name;
         readonly attribute string location;
         NoxReading get_reading();
         void activate();
         void deactivate();
         void reset();
     } ;

    interface RegionalCentre {
        readonly attribute string name;
        readonly attribute string location_name;
        readonly attribute Log_of_alarm_readings log;
        void raise_alarm (in NoxReading alarmReading);
        Set_of_readings take_readings();
        void add_monitoring_station(in string station_name, in string station_location, in string station_ior);
    };
};