module CAQ {

    struct NoxReading {
        long long time;
        long long date;
        string station_name;
        long reading_value;
    };
    struct Station {
        string name;
        string location;
    };

    typedef sequence<NoxReading> Log_of_alarm_readings;
    typedef sequence<NoxReading> Set_of_Readings;

    //Monitoring Station

    interface MonitoringStation {
        //typedef sequence<NoxReading> Set_of_Readings;
        readonly attribute Set_of_Readings readingsLog;
        attribute string name;
        attribute string location;
        attribute boolean status;
        NoxReading get_reading();
        void activate();
        void deactivate();
        void reset();
     } ;

    //Local Server

    interface RegionalCentre {
        typedef sequence<Station> station_list;
        typedef sequence<NoxReading> Log_of_alarm_readings;
        readonly attribute Set_of_Readings readingsLog;
        attribute string name;
        attribute string location;
        void takeReadings();
        void add_monitoring_station(in string station_name, in string station_location);
    };

    //Monitoring Center
    interface MonitoringCenter {
        typedef sequence<NoxReading> Set_of_Readings;
        void raise_alarm(in NoxReading alarm_reading);
        readonly attribute Set_of_Readings readingsLog;
        void register_agency(in string who, in string contact_details, in string area_of_interest);
        void register_local_server(in string server_name);
        void takeReadings(in string name);
    };
};