module CAQ {

    struct NoxReading {
        long long time;
        long long date;
        string station_name;
        long reading_value;
    };
    struct Station {
        string name;
        string location;
    };

    struct Agency {
        string name;
        string locationOfInterest;
        string contactNumber;
    };

    typedef sequence<NoxReading> Log_of_alarm_readings;
    typedef sequence<NoxReading> Set_of_Readings;

    //Monitoring Station

    interface MonitoringStation {
        //typedef sequence<NoxReading> Set_of_Readings;
        readonly attribute Set_of_Readings readingsLog;
        attribute string name;
        attribute string location;
        attribute boolean status;
        NoxReading get_reading();
        void activate();
        void deactivate();
        void reset();
     } ;

    //Local Server

    interface RegionalCentre {
        typedef sequence<Station> station_list;
        typedef sequence<NoxReading> Log_of_alarm_readings;
        readonly attribute Set_of_Readings readingsLog;
        readonly attribute station_list stations;
        attribute string name;
        attribute string location;
        void takeReadings();
        void raise_alarm(in NoxReading reading);
        void add_monitoring_station(in string station_name, in string station_location);
    };

    //Monitoring Center
    interface MonitoringCenter {
        typedef sequence<NoxReading> Set_of_Readings;
        typedef sequence<Station> stationList;
        readonly attribute stationList localServers;
        readonly attribute stationList monitoringStations;
        void raise_alarm(in NoxReading alarm_reading);
        void register_agency(in Agency agencyObject);
        void register_local_server(in Station station_name);
        void register_monitoring_station(in Station station_name);
        void takeReadings(in string name);

    };
};